### ISSUE TITLE
Classes in Java artifact do not match the protos shipped with it

### ISSUE THREAD

**Issue by thesamet** [googleapis/java-common-protos#134]
In the 2.1.0 jar, google/api/endpoint.proto contains a `repeated string features = 4`, however the corresponding Java class file doesn't have any of the methods corresponding to this field.

#### Steps to reproduce

```
$ mkdir tmp && cd tmp
$ curl https://repo1.maven.org/maven2/com/google/api/grpc/proto-google-common-protos/2.1.0/proto-google-common-protos-2.1.0.jar -O
$ less google/api/endpoint.proto   # observe Endpoint has a field features
$ javap  com.google.api.Endpoint | grep -i feature | wc -l
0 
```

It looks like getters for `features` are not there. Seemingly the code has been generated with a different version of the protos.

**Comment by chingor13** [comment]
Thanks for bringing this to our attention. Our automation to update the generated code is not correctly copying the associated proto files with it.

**Comment by chingor13** [comment]
FYI, the removal of this field was in https://github.com/googleapis/java-common-protos/pull/35 and caused this library to go to 2.0.0

**Comment by Tochemey** [comment]
@chingor13 Is there any update on this? Thanks

**Comment by virusdave** [comment]
Seconding the question on updates.

**Comment by Tochemey** [comment]
@chingor13 is there any good news upcoming on this ticket? Thanks

**Comment by gajones155** [comment]
@chingor13 I'm seeing the same issue with the latest 2.2.1 release where `com/google/api/Visibility.class` exists but there's no corresponding `google/api/visibility.proto`.
