### ISSUE TITLE
META-INF/INDEX.LIST:1:1: unexpected label: JarIndex-Version when using proto-google-common-protos 

### ISSUE THREAD

**Issue by chemouna** [googleapis/java-common-protos#310]
Hi, i imported `com.google.api.grpc:proto-google-common-protos:1.18.0` in an android app and i'm using [wire](https://github.com/square/wire) to compile proto files from it but when i build it i keep getting the following error:

`Syntax error incom.google.api.grpc/proto-google-common-protos/1.18.0/b69bc5942255dc9dd2d2de432c4b99a5b483679/proto-google-common-protos-1.18.0.jar/META-INF/INDEX.LIST:1:1: unexpected label: JarIndex-Version`

any input into how to fix this issue ?
thank you

**Comment by Neenu1995** [comment]
Hi @chemouna ,
Can you confirm that you are experiencing the issue with the latest version of [proto-google-common-protos](https://github.com/googleapis/java-common-protos/releases/tag/v2.7.4)?

**Comment by meltsufin** [comment]
Unresponsive user. Closing.
